### ISSUE TITLE
osx-arm64 build is broken

### ISSUE THREAD

**Issue by isuruf** [conda-forge/meshpy-feedstock#7]
Needs a release with https://github.com/inducer/meshpy/commit/3d31449724a9c8aa72380fddd8dee18bdbfe487e#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

cc @inducer

**Comment by inducer** [comment]
But it built successfully? Do we need better tests?

Anywho, #8. Needed a release anyway.

One thing I'm concerned about is that both TetGen and Triangle use fancy "robust geometric primitives" that reconfigure the floating point unit (to pick rounding modes). That may all need some work on ARM. (i.e. I'm worried that even if we get them build, they may not work as intended.)

**Comment by isuruf** [comment]
> But it built successfully? Do we need better tests?

It did, but we are disabling the tests for `osx-arm64`. That's because we are cross compiling and has no way of running tests on CI and a person with access who is running a daily cron job gave the test results to me.

> One thing I'm concerned about is that both TetGen and Triangle use fancy "robust geometric primitives" that reconfigure the floating point unit (to pick rounding modes). That may all need some work on ARM. (i.e. I'm worried that even if we get them build, they may not work as intended.)

Hmm, we might need better tests.

**Comment by isuruf** [comment]
works now and pytest tests pass, but they might not indicate that it works on ARM

**Comment by inducer** [comment]
Thanks for checking! That's good enough for me. Let's wait until somebody complains.
